//! Core types for the companion agent.

use serde::{Deserialize, Serialize};

pub use crate::bond::BondLevel;

/// An urge specification produced by an instinct.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UrgeSpec {
    pub instinct_name: String,
    pub reason: String,
    /// 0.0 (ignore) to 1.0 (act immediately).
    pub urgency: f64,
    pub suggested_message: String,
    pub action: Option<String>,
    pub context: serde_json::Value,
    /// Used for deduplication — if a pending urge has the same key, boost instead.
    pub cooldown_key: String,
}

impl UrgeSpec {
    pub fn new(instinct_name: &str, reason: &str, urgency: f64) -> Self {
        Self {
            instinct_name: instinct_name.to_string(),
            reason: reason.to_string(),
            urgency,
            suggested_message: String::new(),
            action: None,
            context: serde_json::json!({}),
            cooldown_key: String::new(),
        }
    }

    pub fn with_cooldown(mut self, key: &str) -> Self {
        self.cooldown_key = key.to_string();
        self
    }

    pub fn with_context(mut self, ctx: serde_json::Value) -> Self {
        self.context = ctx;
        self
    }

    pub fn with_message(mut self, msg: &str) -> Self {
        self.suggested_message = msg.to_string();
        self
    }
}

/// Read-only snapshot of companion state for instinct evaluation.
#[derive(Debug, Clone)]
pub struct CompanionState {
    pub last_interaction_ts: f64,
    pub current_ts: f64,
    pub session_active: bool,
    pub conversation_turn_count: usize,
    pub recent_valence_avg: Option<f64>,
    pub pending_triggers: Vec<serde_json::Value>,
    pub active_patterns: Vec<serde_json::Value>,
    pub open_conflicts_count: usize,
    pub memory_count: i64,
    pub config_user_name: String,
    // Bond state
    pub bond_level: BondLevel,
    pub bond_score: f64,
    // Evolution state
    pub formality: f64,
    pub opinions_count: usize,
    pub shared_references_count: usize,
    /// Whether bond level changed on the last interaction.
    pub bond_level_changed: bool,
}

/// Response from handle_message().
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentResponse {
    pub message: String,
    pub memories_recalled: usize,
    pub urges_delivered: Vec<String>,
    pub tool_calls_made: Vec<String>,
}

/// A stored urge row from SQLite.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Urge {
    pub urge_id: String,
    pub instinct_name: String,
    pub reason: String,
    pub urgency: f64,
    pub suggested_message: String,
    pub action: Option<String>,
    pub context: serde_json::Value,
    pub cooldown_key: String,
    pub status: String,
    pub created_at: f64,
    pub delivered_at: Option<f64>,
    pub expires_at: Option<f64>,
    pub boost_count: i64,
}

/// A proactive message generated by background cognition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProactiveMessage {
    pub text: String,
    pub urge_ids: Vec<String>,
    pub generated_at: f64,
}
