//! Autonomous Brain — data-driven thinking without LLM involvement.
//!
//! The brain is the DB's own "consciousness": it scans its data for interesting
//! signals, scores them, orients for context, and emits candidates that the
//! companion layer converts into urges. When nothing interesting is found
//! internally, homeostatic drives push the system to seek external information
//! (RSS, weather, news) — like a human turning on the TV when bored.
//!
//! # Signal Model
//!
//! Every observation is classified into one of four signal types:
//!
//! - **PredictionError**: reality ≠ expected (friend usually replies within 1h,
//!   it's been 6h; budget spending rate jumped)
//! - **Tension**: unresolved pressure building (3 overdue tasks, conflict count
//!   rising, inbox growing faster than processing)
//! - **Opportunity**: favorable conditions detected (weather window for planned
//!   hike, contact's birthday approaching, price drop on watched item)
//! - **Uncertainty**: insufficient data to decide — triggers external fetching
//!   (stale weather data, no news in 6h, missing context for a decision)
//!
//! # Homeostatic Drives
//!
//! Four drives oscillate between satiation and hunger, controlling the system's
//! rhythm and preventing both spam and stagnation:
//!
//! - `information_hunger`: rises when no new data arrives, decays on fresh input
//! - `novelty_hunger`: rises when signals are repetitive, decays on novel patterns
//! - `tension_pressure`: rises with unresolved tensions, decays as they resolve
//! - `usefulness_pressure`: rises when outputs are ignored, raises threshold
//!   (more selective, NOT more spammy)
//!
//! # Architecture
//!
//! ```text
//! ┌─────────────────────────────────────────────────────────┐
//! │                    brain_tick()                          │
//! │                                                         │
//! │  1. Update homeostatic drives from recent events        │
//! │  2. Collect BrainCandidates from:                       │
//! │     a. Wrapped instinct UrgeSpecs (via signal_type_of)  │
//! │     b. Native Detectors (pattern break, forward proj.)  │
//! │  3. Score candidates (signal × drives × source_ema)     │
//! │  4. Orient top candidates (cheap context enrichment)    │
//! │  5. Apply adaptive threshold (driven by usefulness)     │
//! │  6. Emit survivors → urge queue                         │
//! │  7. Adjust scan interval from drive volatility          │
//! └─────────────────────────────────────────────────────────┘
//! ```

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

// ══════════════════════════════════════════════════════════════════════════════
// § 1  Signal Types
// ══════════════════════════════════════════════════════════════════════════════

/// The four fundamental signal types that every brain observation is classified
/// into. Modeled after predictive processing / free energy minimization in
/// neuroscience — the brain cares about surprises, pressures, windows, and gaps.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SignalType {
    /// Reality ≠ expected. Something deviated from the learned baseline.
    /// Examples: friend didn't reply (usually fast), spending spike, routine broken.
    PredictionError,

    /// Unresolved pressure accumulating. Needs action to relieve.
    /// Examples: overdue tasks piling up, inbox growing, conflict escalating.
    Tension,

    /// Favorable conditions detected. Time-bounded window to act.
    /// Examples: weather window for hike, birthday approaching, sale on wishlist item.
    Opportunity,

    /// Insufficient data to make a decision. Triggers external fetching.
    /// Examples: stale weather, no news in 6h, ambiguous scheduling conflict.
    Uncertainty,
}

impl SignalType {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::PredictionError => "prediction_error",
            Self::Tension => "tension",
            Self::Opportunity => "opportunity",
            Self::Uncertainty => "uncertainty",
        }
    }

    /// Base weight for scoring. PredictionError is most salient (surprises
    /// demand attention), Uncertainty is lowest (just triggers info-seeking).
    pub fn base_weight(self) -> f64 {
        match self {
            Self::PredictionError => 1.0,
            Self::Tension => 0.85,
            Self::Opportunity => 0.75,
            Self::Uncertainty => 0.5,
        }
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// § 2  Brain Candidate
// ══════════════════════════════════════════════════════════════════════════════

/// A candidate observation from the brain's scan — either wrapped from an
/// instinct UrgeSpec or generated by a native Detector.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BrainCandidate {
    /// Unique ID for deduplication and feedback tracking.
    pub candidate_id: String,

    /// Where this candidate came from.
    pub source: CandidateSource,

    /// Classified signal type (inferred or explicit).
    pub signal_type: SignalType,

    /// Raw urgency from the source (0.0–1.0).
    pub raw_urgency: f64,

    /// Computed brain score after drive modulation and source EMA.
    pub brain_score: f64,

    /// Human-readable reason for this signal.
    pub reason: String,

    /// Suggested message/action text.
    pub suggested_message: String,

    /// Optional action identifier (tool call, fetch, etc.).
    pub action: Option<String>,

    /// Structured context payload.
    pub context: serde_json::Value,

    /// Cooldown key for deduplication.
    pub cooldown_key: String,

    /// Orientation notes added during the orient step.
    pub orientation: Option<OrientationNote>,

    /// Timestamp when this candidate was generated.
    pub created_at: f64,
}

/// Where a BrainCandidate originated.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum CandidateSource {
    /// Wrapped from an existing instinct's UrgeSpec output.
    Instinct {
        instinct_name: String,
        /// Original instinct category (for signal type inference).
        category: String,
    },
    /// Generated by a native brain Detector (pattern break, forward projection, etc.).
    Detector {
        detector_name: String,
    },
    /// External data fetch triggered by Uncertainty signal.
    ExternalFetch {
        fetch_type: String,
    },
}

impl CandidateSource {
    pub fn source_key(&self) -> String {
        match self {
            Self::Instinct { instinct_name, .. } => format!("instinct:{instinct_name}"),
            Self::Detector { detector_name } => format!("detector:{detector_name}"),
            Self::ExternalFetch { fetch_type } => format!("fetch:{fetch_type}"),
        }
    }
}

/// Context notes added during the cheap orientation step — verifies the
/// signal is still valid without needing an LLM call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrientationNote {
    /// Was the signal confirmed as still valid after context check?
    pub confirmed: bool,
    /// Brief explanation of why the signal was confirmed or rejected.
    pub note: String,
    /// Adjusted urgency after orientation (may increase or decrease).
    pub adjusted_urgency: f64,
}

// ══════════════════════════════════════════════════════════════════════════════
// § 3  Homeostatic Drives
// ══════════════════════════════════════════════════════════════════════════════

/// The four homeostatic drives that control the brain's rhythm. Each oscillates
/// between 0.0 (sated) and 1.0 (hungry/pressured), modulating what signals
/// pass the scoring threshold.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Homeostasis {
    /// Rises when no new data arrives. Decays on fresh input.
    /// High → brain becomes more interested in any information.
    pub information_hunger: f64,

    /// Rises when signals are repetitive / same sources dominate.
    /// High → brain weights novel sources and signal types higher.
    pub novelty_hunger: f64,

    /// Rises with unresolved tensions (overdue tasks, conflicts, etc.).
    /// High → Tension signals get priority, brain focuses on resolution.
    pub tension_pressure: f64,

    /// Rises when the user ignores or dismisses outputs.
    /// High → brain RAISES threshold (becomes more selective, not spammier).
    pub usefulness_pressure: f64,

    /// Timestamp of last drive update.
    pub last_updated: f64,
}

impl Default for Homeostasis {
    fn default() -> Self {
        Self {
            information_hunger: 0.3,   // slightly hungry on startup
            novelty_hunger: 0.3,
            tension_pressure: 0.1,     // assume calm start
            usefulness_pressure: 0.2,  // slightly cautious by default
            last_updated: 0.0,
        }
    }
}

impl Homeostasis {
    /// Compute the adaptive surfacing threshold. Higher usefulness_pressure
    /// means higher threshold → fewer signals pass → more selective.
    /// Range: 0.25 (very permissive) to 0.85 (very selective).
    pub fn surfacing_threshold(&self) -> f64 {
        let base = 0.35;
        let usefulness_boost = self.usefulness_pressure * 0.5;
        (base + usefulness_boost).clamp(0.25, 0.85)
    }

    /// Compute the desired scan interval in seconds based on drive volatility.
    /// High volatility (active drives) → faster scanning (30s).
    /// Low volatility (all calm) → slower scanning (300s).
    pub fn scan_interval_secs(&self) -> f64 {
        let volatility = self.drive_volatility();
        // Map volatility [0, 1] → interval [300, 30]
        let fast = 30.0;
        let slow = 300.0;
        slow - (volatility * (slow - fast))
    }

    /// Overall drive volatility — how "activated" the brain is.
    /// Average of all drives, weighted by their salience.
    pub fn drive_volatility(&self) -> f64 {
        let weighted = self.information_hunger * 0.3
            + self.novelty_hunger * 0.2
            + self.tension_pressure * 0.3
            + self.usefulness_pressure * 0.2;
        weighted.clamp(0.0, 1.0)
    }

    /// Update information hunger based on seconds since last data event.
    /// Rises exponentially as time without new data increases.
    pub fn update_information_hunger(&mut self, secs_since_last_event: f64) {
        // Half-life: hunger reaches 0.5 at ~600s (10min) of no data
        let hunger = 1.0 - (-secs_since_last_event / 900.0).exp();
        self.information_hunger = hunger.clamp(0.0, 1.0);
    }

    /// Feed information hunger — decays toward 0 when fresh data arrives.
    pub fn feed_information(&mut self, amount: f64) {
        self.information_hunger = (self.information_hunger - amount).clamp(0.0, 1.0);
    }

    /// Update novelty hunger based on the diversity of recent signal sources.
    /// Low diversity → hunger rises. High diversity → hunger falls.
    pub fn update_novelty_hunger(&mut self, source_diversity: f64) {
        // source_diversity: 0.0 (all same source) to 1.0 (all different)
        self.novelty_hunger = (1.0 - source_diversity).clamp(0.0, 1.0);
    }

    /// Update tension pressure from the count of unresolved tensions.
    pub fn update_tension_pressure(&mut self, unresolved_count: usize) {
        // Saturates around 10 unresolved tensions
        let pressure = 1.0 - (-0.2 * unresolved_count as f64).exp();
        self.tension_pressure = pressure.clamp(0.0, 1.0);
    }

    /// Update usefulness pressure based on recent acceptance rate.
    /// acceptance_rate: 0.0 (everything ignored) to 1.0 (everything acted on).
    pub fn update_usefulness(&mut self, acceptance_rate: f64) {
        // Invert: low acceptance → high pressure
        self.usefulness_pressure = (1.0 - acceptance_rate).clamp(0.0, 1.0);
    }

    /// Decay all drives toward their resting state over a time delta.
    /// Called each brain tick to prevent drives from sticking at extremes.
    pub fn decay(&mut self, dt_secs: f64) {
        let decay_rate = 0.001; // per second — full decay ~16min
        let factor = (-decay_rate * dt_secs).exp();

        // Decay toward resting values
        self.information_hunger = lerp(0.2, self.information_hunger, factor);
        self.novelty_hunger = lerp(0.2, self.novelty_hunger, factor);
        self.tension_pressure = lerp(0.05, self.tension_pressure, factor);
        self.usefulness_pressure = lerp(0.15, self.usefulness_pressure, factor);
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// § 4  Source Feedback Tracker (EMA-based learning)
// ══════════════════════════════════════════════════════════════════════════════

/// Tracks per-source, per-signal-type feedback using Exponential Moving Average.
/// This is how the brain learns which sources produce useful signals.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceFeedback {
    /// Map from source_key → signal_type → EMA of usefulness (0.0–1.0).
    pub ema: HashMap<String, HashMap<String, f64>>,

    /// Total outcomes recorded per source (for confidence weighting).
    pub outcome_count: HashMap<String, u64>,
}

impl Default for SourceFeedback {
    fn default() -> Self {
        Self {
            ema: HashMap::new(),
            outcome_count: HashMap::new(),
        }
    }
}

impl SourceFeedback {
    /// EMA smoothing factor. Higher = more weight on recent outcomes.
    const ALPHA: f64 = 0.15;

    /// Default EMA for unknown source/signal combinations (mildly optimistic).
    const DEFAULT_EMA: f64 = 0.5;

    /// Minimum EMA before a source is considered "spam" (auto-suppressed).
    const SPAM_THRESHOLD: f64 = 0.1;

    /// Record an outcome for a source/signal combination.
    /// `reward`: 1.0 = acted on, 0.5 = read, 0.0 = ignored/dismissed.
    pub fn record(&mut self, source_key: &str, signal_type: SignalType, reward: f64) {
        let signal_str = signal_type.as_str().to_string();
        let current = self.get(source_key, signal_type);
        let new_ema = current * (1.0 - Self::ALPHA) + reward * Self::ALPHA;

        self.ema
            .entry(source_key.to_string())
            .or_default()
            .insert(signal_str, new_ema);

        *self.outcome_count
            .entry(source_key.to_string())
            .or_insert(0) += 1;
    }

    /// Get the current EMA for a source/signal combination.
    pub fn get(&self, source_key: &str, signal_type: SignalType) -> f64 {
        self.ema
            .get(source_key)
            .and_then(|m| m.get(signal_type.as_str()))
            .copied()
            .unwrap_or(Self::DEFAULT_EMA)
    }

    /// How many outcomes have been recorded for this source.
    pub fn confidence(&self, source_key: &str) -> u64 {
        self.outcome_count.get(source_key).copied().unwrap_or(0)
    }

    /// Is this source considered spam? (EMA below threshold with sufficient data)
    pub fn is_spam(&self, source_key: &str, signal_type: SignalType) -> bool {
        self.confidence(source_key) >= 5
            && self.get(source_key, signal_type) < Self::SPAM_THRESHOLD
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// § 5  Signal Type Inference (3-layer heuristic)
// ══════════════════════════════════════════════════════════════════════════════

/// Per-instinct default signal type mappings. Instincts that don't appear
/// here fall through to keyword heuristics.
static INSTINCT_SIGNAL_DEFAULTS: &[(&str, SignalType)] = &[
    // PredictionError — something deviated from expected
    ("contact_silence", SignalType::PredictionError),
    ("pattern_break", SignalType::PredictionError),
    ("routine_deviation", SignalType::PredictionError),
    ("spending_anomaly", SignalType::PredictionError),
    ("sleep_anomaly", SignalType::PredictionError),
    ("mood_shift", SignalType::PredictionError),
    ("energy_shift", SignalType::PredictionError),
    ("activity_reflector", SignalType::PredictionError),

    // Tension — unresolved pressure
    ("open_loop", SignalType::Tension),
    ("overdue_task", SignalType::Tension),
    ("conflict_alerting", SignalType::Tension),
    ("cognitive_load", SignalType::Tension),
    ("deadline_pressure", SignalType::Tension),
    ("inbox_pressure", SignalType::Tension),
    ("decision_fatigue", SignalType::Tension),
    ("unprocessed_backlog", SignalType::Tension),
    ("goal_drift", SignalType::Tension),
    ("health_check", SignalType::Tension),

    // Opportunity — favorable window
    ("weather_window", SignalType::Opportunity),
    ("birthday_reminder", SignalType::Opportunity),
    ("activity_recommender", SignalType::Opportunity),
    ("connection_weaver", SignalType::Opportunity),
    ("learning_moment", SignalType::Opportunity),
    ("habit_streak", SignalType::Opportunity),
    ("bond_milestone", SignalType::Opportunity),
    ("gratitude", SignalType::Opportunity),
    ("skill_gap", SignalType::Opportunity),
    ("serendipity", SignalType::Opportunity),
    ("momentum", SignalType::Opportunity),
    ("growth_edge", SignalType::Opportunity),

    // Uncertainty — need more data
    ("stale_data", SignalType::Uncertainty),
    ("context_bridge", SignalType::Uncertainty),
    ("check_in", SignalType::Uncertainty),
    ("curiosity", SignalType::Uncertainty),
    ("exploration", SignalType::Uncertainty),
];

/// Keyword patterns for signal type inference when no explicit mapping exists.
static KEYWORD_PATTERNS: &[(&[&str], SignalType)] = &[
    (&["overdue", "missed", "late", "forgot", "anomaly", "unusual", "unexpected", "deviat"],
     SignalType::PredictionError),
    (&["pending", "backlog", "conflict", "pressure", "overload", "stuck", "blocked", "urgent"],
     SignalType::Tension),
    (&["birthday", "weather", "window", "opportunity", "sale", "streak", "milestone", "ready"],
     SignalType::Opportunity),
    (&["stale", "unknown", "missing", "check", "fetch", "update", "refresh", "unclear"],
     SignalType::Uncertainty),
];

/// Infer the signal type for a wrapped instinct output using a 3-layer heuristic:
///
/// 1. **Explicit metadata**: if the context JSON contains a `signal_type` field, use it.
/// 2. **Per-instinct default**: lookup in `INSTINCT_SIGNAL_DEFAULTS`.
/// 3. **Keyword heuristics**: scan reason + instinct_name for signal keywords.
/// 4. **Fallback**: `Uncertainty` (safest default — triggers info-seeking, not action).
pub fn infer_signal_type(
    instinct_name: &str,
    reason: &str,
    context: &serde_json::Value,
) -> SignalType {
    // Layer 1: Explicit metadata in context
    if let Some(st) = context.get("signal_type").and_then(|v| v.as_str()) {
        match st {
            "prediction_error" => return SignalType::PredictionError,
            "tension" => return SignalType::Tension,
            "opportunity" => return SignalType::Opportunity,
            "uncertainty" => return SignalType::Uncertainty,
            _ => {}
        }
    }

    // Layer 2: Per-instinct default
    for &(name, signal) in INSTINCT_SIGNAL_DEFAULTS {
        if instinct_name == name || instinct_name.contains(name) {
            return signal;
        }
    }

    // Layer 3: Keyword heuristics on reason + instinct_name
    let haystack = format!("{} {}", instinct_name, reason).to_lowercase();
    let mut best_match: Option<(usize, SignalType)> = None;

    for &(keywords, signal) in KEYWORD_PATTERNS {
        let hits = keywords.iter()
            .filter(|kw| haystack.contains(**kw))
            .count();
        if hits > 0 {
            if best_match.map_or(true, |(best, _)| hits > best) {
                best_match = Some((hits, signal));
            }
        }
    }

    if let Some((_, signal)) = best_match {
        return signal;
    }

    // Layer 4: Fallback
    SignalType::Uncertainty
}

// ══════════════════════════════════════════════════════════════════════════════
// § 6  Candidate Scoring
// ══════════════════════════════════════════════════════════════════════════════

/// Score a BrainCandidate using the signal type weights, homeostatic drive
/// modulation, and source feedback EMA.
pub fn score_candidate(
    candidate: &BrainCandidate,
    drives: &Homeostasis,
    feedback: &SourceFeedback,
) -> f64 {
    let signal_weight = candidate.signal_type.base_weight();
    let source_key = candidate.source.source_key();

    // Drive modulation: each drive amplifies its related signal types
    let drive_boost = match candidate.signal_type {
        SignalType::PredictionError => 1.0 + drives.novelty_hunger * 0.3,
        SignalType::Tension => 1.0 + drives.tension_pressure * 0.4,
        SignalType::Opportunity => 1.0 + drives.information_hunger * 0.2,
        SignalType::Uncertainty => 1.0 + drives.information_hunger * 0.5,
    };

    // Source EMA: learned reliability of this source for this signal type
    let source_ema = feedback.get(&source_key, candidate.signal_type);

    // Confidence weight: new sources get benefit of doubt, established ones
    // are weighted by their track record
    let confidence = feedback.confidence(&source_key);
    let confidence_weight = if confidence < 3 {
        0.8 // new source — slight discount but not harsh
    } else {
        source_ema
    };

    // Final score
    let score = candidate.raw_urgency
        * signal_weight
        * drive_boost
        * confidence_weight;

    score.clamp(0.0, 1.0)
}

// ══════════════════════════════════════════════════════════════════════════════
// § 7  Orientation (cheap context verification)
// ══════════════════════════════════════════════════════════════════════════════

/// Orientation check results — cheap verification that a signal is still valid.
pub struct OrientationInput {
    /// Current timestamp.
    pub now: f64,
    /// Seconds since last user interaction.
    pub idle_secs: f64,
    /// Number of pending urges already in the queue.
    pub pending_urge_count: usize,
    /// Currently active cooldown keys.
    pub active_cooldowns: Vec<String>,
    /// Current hour of day (0-23) for time-relevance checks.
    pub current_hour: u32,
}

/// Run the cheap orientation step on a scored candidate. This verifies the
/// signal is still valid without needing an LLM call. Returns None if the
/// candidate should be dropped entirely.
pub fn orient(
    candidate: &BrainCandidate,
    input: &OrientationInput,
) -> Option<OrientationNote> {
    // Check 1: Cooldown — if this cooldown key is active, suppress
    if input.active_cooldowns.contains(&candidate.cooldown_key) {
        return Some(OrientationNote {
            confirmed: false,
            note: "Cooldown active for this signal".into(),
            adjusted_urgency: 0.0,
        });
    }

    // Check 2: Queue saturation — if too many pending urges, raise bar
    let queue_penalty = if input.pending_urge_count > 5 {
        0.8 // penalize when queue is full
    } else {
        1.0
    };

    // Check 3: Time relevance — some signals are less relevant at night
    let time_factor = match candidate.signal_type {
        SignalType::Opportunity => {
            // Opportunities about activities are less relevant at 2am
            if input.current_hour >= 23 || input.current_hour < 6 {
                0.5
            } else {
                1.0
            }
        }
        SignalType::Tension => {
            // Tensions can wait until morning
            if input.current_hour >= 23 || input.current_hour < 7 {
                0.6
            } else {
                1.0
            }
        }
        SignalType::PredictionError => 1.0, // surprises are always relevant
        SignalType::Uncertainty => {
            // Don't trigger fetches at night
            if input.current_hour >= 22 || input.current_hour < 6 {
                0.3
            } else {
                1.0
            }
        }
    };

    // Check 4: Staleness — candidates older than 10 minutes lose relevance
    let age = input.now - candidate.created_at;
    let freshness = if age > 600.0 {
        (1.0 - (age - 600.0) / 1200.0).max(0.1)
    } else {
        1.0
    };

    let adjusted = candidate.brain_score * queue_penalty * time_factor * freshness;

    if adjusted < 0.05 {
        return None; // drop entirely — too weak after orientation
    }

    Some(OrientationNote {
        confirmed: adjusted > 0.15,
        note: format!(
            "queue={:.1} time={:.1} fresh={:.2}",
            queue_penalty, time_factor, freshness
        ),
        adjusted_urgency: adjusted,
    })
}

// ══════════════════════════════════════════════════════════════════════════════
// § 8  Brain State (persisted across ticks)
// ══════════════════════════════════════════════════════════════════════════════

/// The complete brain state persisted between ticks. Serialized to the DB
/// as a JSON blob in a cognitive_nodes entry or dedicated table.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BrainState {
    /// Homeostatic drives controlling rhythm and thresholds.
    pub drives: Homeostasis,

    /// Per-source feedback tracker for learning.
    pub feedback: SourceFeedback,

    /// Recent signal type distribution (for novelty tracking).
    pub recent_signal_counts: HashMap<String, u64>,

    /// Recent source distribution (for novelty tracking).
    pub recent_source_counts: HashMap<String, u64>,

    /// Number of brain ticks performed since startup.
    pub tick_count: u64,

    /// Timestamp of last tick.
    pub last_tick_at: f64,

    /// Timestamp of last external data event.
    pub last_data_event_at: f64,

    /// Total candidates emitted (lifetime).
    pub total_emitted: u64,

    /// Total candidates suppressed (lifetime).
    pub total_suppressed: u64,
}

impl Default for BrainState {
    fn default() -> Self {
        Self {
            drives: Homeostasis::default(),
            feedback: SourceFeedback::default(),
            recent_signal_counts: HashMap::new(),
            recent_source_counts: HashMap::new(),
            tick_count: 0,
            last_tick_at: 0.0,
            last_data_event_at: 0.0,
            total_emitted: 0,
            total_suppressed: 0,
        }
    }
}

impl BrainState {
    /// Compute source diversity (0.0 = all same source, 1.0 = uniform distribution).
    /// Uses Shannon entropy normalized by log(N).
    pub fn source_diversity(&self) -> f64 {
        let total: u64 = self.recent_source_counts.values().sum();
        if total == 0 {
            return 0.0;
        }
        let n = self.recent_source_counts.len();
        if n <= 1 {
            return 0.0;
        }

        let total_f = total as f64;
        let entropy: f64 = self.recent_source_counts.values()
            .filter(|&&c| c > 0)
            .map(|&c| {
                let p = c as f64 / total_f;
                -p * p.ln()
            })
            .sum();

        let max_entropy = (n as f64).ln();
        if max_entropy == 0.0 { 0.0 } else { entropy / max_entropy }
    }

    /// Record that a candidate was emitted to the urge queue.
    pub fn record_emission(&mut self, candidate: &BrainCandidate) {
        let signal_key = candidate.signal_type.as_str().to_string();
        let source_key = candidate.source.source_key();

        *self.recent_signal_counts.entry(signal_key).or_insert(0) += 1;
        *self.recent_source_counts.entry(source_key).or_insert(0) += 1;
        self.total_emitted += 1;
    }

    /// Record that a candidate was suppressed.
    pub fn record_suppression(&mut self) {
        self.total_suppressed += 1;
    }

    /// Decay recent counters to prevent them from growing unbounded.
    /// Called periodically (e.g., every 10 ticks or every 10 minutes).
    pub fn decay_recent_counts(&mut self) {
        // Halve all counts — exponential decay
        self.recent_signal_counts.retain(|_, v| {
            *v /= 2;
            *v > 0
        });
        self.recent_source_counts.retain(|_, v| {
            *v /= 2;
            *v > 0
        });
    }

    /// Update all homeostatic drives from the current state.
    pub fn update_drives(&mut self, now: f64, unresolved_tension_count: usize) {
        let dt = now - self.drives.last_updated;
        if dt <= 0.0 {
            return;
        }

        // Natural decay toward resting state
        self.drives.decay(dt);

        // Information hunger from time since last data event
        let secs_since_data = now - self.last_data_event_at;
        self.drives.update_information_hunger(secs_since_data);

        // Novelty hunger from source diversity
        let diversity = self.source_diversity();
        self.drives.update_novelty_hunger(diversity);

        // Tension pressure from unresolved count
        self.drives.update_tension_pressure(unresolved_tension_count);

        // Usefulness pressure is updated via record_feedback(), not here

        self.drives.last_updated = now;
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// § 9  Brain Tick Result
// ══════════════════════════════════════════════════════════════════════════════

/// The output of a single brain_tick() — what the companion layer uses to
/// feed the urge queue.
#[derive(Debug, Clone)]
pub struct BrainTickResult {
    /// Candidates that passed scoring + orientation + threshold.
    pub emitted: Vec<BrainCandidate>,

    /// Number of candidates that were suppressed.
    pub suppressed_count: usize,

    /// Recommended interval until the next tick (seconds).
    pub next_tick_secs: f64,

    /// Whether the brain is "hungry" — external fetching should be triggered.
    pub should_fetch_external: bool,

    /// Current drive snapshot (for debugging/logging).
    pub drives_snapshot: Homeostasis,
}

/// Run a complete brain tick. This is the main entry point called by the
/// companion's think cycle.
///
/// # Arguments
/// - `state`: mutable brain state (persisted across ticks)
/// - `candidates`: all BrainCandidates collected this tick (wrapped instincts + detectors)
/// - `orientation_input`: context for the orientation step
/// - `max_emit`: maximum candidates to emit per tick (prevents flooding)
pub fn brain_tick(
    state: &mut BrainState,
    candidates: Vec<BrainCandidate>,
    orientation_input: &OrientationInput,
    max_emit: usize,
) -> BrainTickResult {
    state.tick_count += 1;
    let now = orientation_input.now;
    state.last_tick_at = now;

    // Decay recent counters every 10 ticks
    if state.tick_count % 10 == 0 {
        state.decay_recent_counts();
    }

    let threshold = state.drives.surfacing_threshold();
    let mut scored: Vec<BrainCandidate> = Vec::with_capacity(candidates.len());

    // Score all candidates
    for mut candidate in candidates {
        // Skip spam sources
        let source_key = candidate.source.source_key();
        if state.feedback.is_spam(&source_key, candidate.signal_type) {
            state.record_suppression();
            continue;
        }

        candidate.brain_score = score_candidate(&candidate, &state.drives, &state.feedback);
        scored.push(candidate);
    }

    // Sort by brain_score descending
    scored.sort_by(|a, b| b.brain_score.partial_cmp(&a.brain_score).unwrap_or(std::cmp::Ordering::Equal));

    // Orient and filter
    let mut emitted = Vec::new();
    let mut suppressed_count = 0;

    for mut candidate in scored {
        if emitted.len() >= max_emit {
            suppressed_count += 1;
            continue;
        }

        match orient(&candidate, orientation_input) {
            Some(note) if note.confirmed && note.adjusted_urgency >= threshold => {
                candidate.brain_score = note.adjusted_urgency;
                candidate.orientation = Some(note);
                state.record_emission(&candidate);
                emitted.push(candidate);
            }
            Some(_) | None => {
                suppressed_count += 1;
                state.record_suppression();
            }
        }
    }

    // Determine if external fetching should happen
    let should_fetch = state.drives.information_hunger > 0.6
        || (state.drives.information_hunger > 0.4
            && emitted.is_empty()
            && state.tick_count > 3);

    let next_tick = state.drives.scan_interval_secs();

    BrainTickResult {
        emitted,
        suppressed_count,
        next_tick_secs: next_tick,
        should_fetch_external: should_fetch,
        drives_snapshot: state.drives.clone(),
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// § 10  Utility
// ══════════════════════════════════════════════════════════════════════════════

/// Linear interpolation: lerp(target, current, factor).
/// factor=1 → current, factor=0 → target.
fn lerp(target: f64, current: f64, factor: f64) -> f64 {
    target + (current - target) * factor
}

// ══════════════════════════════════════════════════════════════════════════════
// § 11  Tests
// ══════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    fn make_candidate(signal: SignalType, urgency: f64, source: &str) -> BrainCandidate {
        BrainCandidate {
            candidate_id: uuid7::uuid7().to_string(),
            source: CandidateSource::Instinct {
                instinct_name: source.to_string(),
                category: "awareness".to_string(),
            },
            signal_type: signal,
            raw_urgency: urgency,
            brain_score: 0.0,
            reason: format!("Test signal from {source}"),
            suggested_message: "Test message".into(),
            action: None,
            context: serde_json::json!({}),
            cooldown_key: format!("test:{source}"),
            orientation: None,
            created_at: 1000.0,
        }
    }

    fn default_orientation() -> OrientationInput {
        OrientationInput {
            now: 1000.0,
            idle_secs: 60.0,
            pending_urge_count: 0,
            active_cooldowns: vec![],
            current_hour: 14, // 2pm — normal hours
        }
    }

    #[test]
    fn test_signal_type_base_weights() {
        assert!(SignalType::PredictionError.base_weight() > SignalType::Tension.base_weight());
        assert!(SignalType::Tension.base_weight() > SignalType::Opportunity.base_weight());
        assert!(SignalType::Opportunity.base_weight() > SignalType::Uncertainty.base_weight());
    }

    #[test]
    fn test_homeostasis_default_threshold() {
        let h = Homeostasis::default();
        let t = h.surfacing_threshold();
        assert!(t > 0.3 && t < 0.6, "Default threshold should be moderate: {t}");
    }

    #[test]
    fn test_usefulness_pressure_raises_threshold() {
        let mut h = Homeostasis::default();
        let t1 = h.surfacing_threshold();
        h.usefulness_pressure = 0.9;
        let t2 = h.surfacing_threshold();
        assert!(t2 > t1, "High usefulness pressure should raise threshold");
    }

    #[test]
    fn test_scan_interval_varies_with_volatility() {
        let mut h = Homeostasis::default();
        h.information_hunger = 0.1;
        h.novelty_hunger = 0.1;
        h.tension_pressure = 0.1;
        h.usefulness_pressure = 0.1;
        let slow = h.scan_interval_secs();

        h.information_hunger = 0.9;
        h.tension_pressure = 0.9;
        let fast = h.scan_interval_secs();

        assert!(fast < slow, "Higher volatility should mean faster scanning");
        assert!(fast >= 30.0 && slow <= 300.0);
    }

    #[test]
    fn test_signal_type_inference_explicit_metadata() {
        let ctx = serde_json::json!({"signal_type": "tension"});
        assert_eq!(infer_signal_type("unknown_instinct", "some reason", &ctx), SignalType::Tension);
    }

    #[test]
    fn test_signal_type_inference_instinct_default() {
        let ctx = serde_json::json!({});
        assert_eq!(infer_signal_type("contact_silence", "friend hasn't replied", &ctx), SignalType::PredictionError);
        assert_eq!(infer_signal_type("open_loop", "3 tasks pending", &ctx), SignalType::Tension);
        assert_eq!(infer_signal_type("weather_window", "clear skies tomorrow", &ctx), SignalType::Opportunity);
    }

    #[test]
    fn test_signal_type_inference_keyword_heuristic() {
        let ctx = serde_json::json!({});
        assert_eq!(infer_signal_type("custom_thing", "overdue payment detected", &ctx), SignalType::PredictionError);
        assert_eq!(infer_signal_type("custom_thing", "backlog is growing", &ctx), SignalType::Tension);
    }

    #[test]
    fn test_signal_type_inference_fallback() {
        let ctx = serde_json::json!({});
        assert_eq!(infer_signal_type("totally_unknown", "nothing matches", &ctx), SignalType::Uncertainty);
    }

    #[test]
    fn test_source_feedback_ema() {
        let mut fb = SourceFeedback::default();
        let src = "instinct:weather_window";

        // Start at default
        assert!((fb.get(src, SignalType::Opportunity) - 0.5).abs() < 0.01);

        // Record positive outcomes
        for _ in 0..10 {
            fb.record(src, SignalType::Opportunity, 1.0);
        }
        assert!(fb.get(src, SignalType::Opportunity) > 0.7);

        // Record negative outcomes
        for _ in 0..20 {
            fb.record(src, SignalType::Opportunity, 0.0);
        }
        assert!(fb.get(src, SignalType::Opportunity) < 0.3);
    }

    #[test]
    fn test_spam_detection() {
        let mut fb = SourceFeedback::default();
        let src = "instinct:annoying_thing";

        // Not enough data yet
        assert!(!fb.is_spam(src, SignalType::Tension));

        // Record lots of ignores
        for _ in 0..10 {
            fb.record(src, SignalType::Tension, 0.0);
        }
        assert!(fb.is_spam(src, SignalType::Tension));
    }

    #[test]
    fn test_candidate_scoring() {
        let drives = Homeostasis::default();
        let feedback = SourceFeedback::default();

        let high = make_candidate(SignalType::PredictionError, 0.9, "anomaly_detector");
        let low = make_candidate(SignalType::Uncertainty, 0.3, "stale_check");

        let score_high = score_candidate(&high, &drives, &feedback);
        let score_low = score_candidate(&low, &drives, &feedback);

        assert!(score_high > score_low, "High urgency PredictionError should score higher than low urgency Uncertainty");
    }

    #[test]
    fn test_orientation_cooldown_suppression() {
        let candidate = make_candidate(SignalType::Tension, 0.8, "test");
        let input = OrientationInput {
            active_cooldowns: vec!["test:test".to_string()],
            ..default_orientation()
        };

        let note = orient(&candidate, &input);
        assert!(note.is_some());
        assert!(!note.unwrap().confirmed);
    }

    #[test]
    fn test_orientation_night_suppression() {
        let mut candidate = make_candidate(SignalType::Uncertainty, 0.5, "fetch");
        candidate.brain_score = 0.5;
        let input = OrientationInput {
            current_hour: 3, // 3am
            ..default_orientation()
        };

        let note = orient(&candidate, &input);
        match note {
            Some(n) => assert!(n.adjusted_urgency < 0.5 * 0.5, "Should be heavily penalized at night"),
            None => {} // also acceptable — dropped entirely
        }
    }

    #[test]
    fn test_brain_tick_basic() {
        let mut state = BrainState::default();
        state.last_data_event_at = 900.0;

        let candidates = vec![
            make_candidate(SignalType::PredictionError, 0.9, "anomaly"),
            make_candidate(SignalType::Tension, 0.7, "overdue"),
            make_candidate(SignalType::Uncertainty, 0.2, "stale"),
        ];

        let input = default_orientation();
        let result = brain_tick(&mut state, candidates, &input, 5);

        // High urgency candidates should pass, low ones may not
        assert!(!result.emitted.is_empty(), "Should emit at least one candidate");
        assert!(result.next_tick_secs >= 30.0 && result.next_tick_secs <= 300.0);
    }

    #[test]
    fn test_brain_tick_respects_max_emit() {
        let mut state = BrainState::default();
        state.last_data_event_at = 999.0;

        let candidates: Vec<_> = (0..10)
            .map(|i| make_candidate(SignalType::PredictionError, 0.9, &format!("source_{i}")))
            .collect();

        let input = default_orientation();
        let result = brain_tick(&mut state, candidates, &input, 3);

        assert!(result.emitted.len() <= 3);
    }

    #[test]
    fn test_source_diversity() {
        let mut state = BrainState::default();

        // Single source → diversity = 0
        state.recent_source_counts.insert("a".into(), 10);
        assert!(state.source_diversity() < 0.01);

        // Two equal sources → high diversity
        state.recent_source_counts.insert("b".into(), 10);
        assert!(state.source_diversity() > 0.9);

        // Highly skewed → low diversity
        state.recent_source_counts.clear();
        state.recent_source_counts.insert("a".into(), 100);
        state.recent_source_counts.insert("b".into(), 1);
        assert!(state.source_diversity() < 0.2);
    }

    #[test]
    fn test_external_fetch_trigger() {
        let mut state = BrainState::default();
        state.drives.information_hunger = 0.8; // very hungry
        state.tick_count = 5;
        state.last_data_event_at = 0.0;

        let input = default_orientation();
        let result = brain_tick(&mut state, vec![], &input, 5);

        assert!(result.should_fetch_external, "High info hunger with no candidates should trigger fetch");
    }
}
